# Generated by Django 5.0.6 on 2024-12-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=100)),
                ('models_spec', models.TextField(help_text='JSON format for models and fields.')),
                ('endpoints_spec', models.TextField(help_text='JSON format for endpoints.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
